# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_api', models.CharField(max_length=512, unique=True, verbose_name='API мойсклад')),
                ('yandex_api', models.CharField(max_length=512, unique=True, verbose_name='API Яндекс')),
                ('wildberries_api', models.CharField(max_length=512, unique=True, verbose_name='API wildberries')),
                ('client_id', models.CharField(max_length=512, unique=True, verbose_name='Client Id Ozon')),
                ('ozon_api', models.CharField(max_length=512, unique=True, verbose_name='API Ozon')),
                ('stock_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя инвентаризация')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('yandex', models.BooleanField(default=False, verbose_name='yandex')),
                ('ozon', models.BooleanField(default=False, verbose_name='ozon')),
                ('wb', models.BooleanField(default=False, verbose_name='wb')),
                ('crontab_dict', models.JSONField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.seller', verbose_name='Связанный парсер')),
            ],
            options={
                'unique_together': {('seller', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Awaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_number', models.CharField(max_length=30, verbose_name='Номер отправления')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('market', models.CharField(max_length=30, verbose_name='Маркетплейс')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.seller', verbose_name='Связанный парсер')),
            ],
            options={
                'verbose_name': 'Ожидающий заказ',
                'verbose_name_plural': 'Ожидающие заказы',
            },
        ),
        migrations.CreateModel(
            name='Awaiting_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50, verbose_name='ID предложения')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('awaiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.awaiting', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Товар ожидающего заказа',
                'verbose_name_plural': 'Товары ожидающих заказов',
            },
        ),
        migrations.CreateModel(
            name='PromoMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50, verbose_name='Маркетплейс')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_market', to='owm.seller')),
            ],
            options={
                'verbose_name': 'Настройки акций маркетплейса',
                'verbose_name_plural': 'Настройки акций маркетплейсов',
                'unique_together': {('seller', 'market')},
            },
        ),
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, verbose_name='ID товара')),
                ('yourprice', models.IntegerField(blank=True, null=True, verbose_name='Ваша цена')),
                ('minprice', models.IntegerField(blank=True, null=True, verbose_name='Мин. цена')),
                ('min_price_fbs', models.IntegerField(blank=True, null=True, verbose_name='Мин. цена FBS')),
                ('min_price_limit_count', models.IntegerField(blank=True, null=True, verbose_name='Мин. цена для лимита')),
                ('min_price_promo', models.IntegerField(blank=True, null=True, verbose_name='Мин. цена для акции')),
                ('limit_count_value', models.IntegerField(blank=True, null=True, verbose_name='Значение лимита')),
                ('use_fbs', models.BooleanField(default=False, verbose_name='Отключить FBS')),
                ('use_limit_count', models.BooleanField(default=False, verbose_name='Отключить лимит')),
                ('use_promo', models.BooleanField(default=False, verbose_name='Отключить участие в акции')),
                ('autoupdate_promo', models.BooleanField(default=False, verbose_name='Автообновление дней акции')),
                ('promo_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='owm.promomarket')),
            ],
            options={
                'verbose_name': 'Настройки акции товара',
                'verbose_name_plural': 'Настройки акций товаров',
                'unique_together': {('promo_market', 'offer_id')},
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.TextField(verbose_name='Значение')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Метаданные',
                'verbose_name_plural': 'Метаданные',
            },
        ),
        migrations.AddConstraint(
            model_name='awaiting',
            constraint=models.UniqueConstraint(fields=['posting_number'], name='unique_posting_number'),
        ),
    ]
