# Generated by Django 5.0.6 on 2025-08-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('settings_dict', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='awaiting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='awaiting_product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='awaiting',
            name='unique_posting_number',
        ),
        migrations.AlterUniqueTogether(
            name='crontab',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value',
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadata_dict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awaiting',
            name='market',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='awaiting',
            name='posting_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='awaiting',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='awaiting_product',
            name='offer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.seller', verbose_name='Связанный парсер'),
        ),
        migrations.AddConstraint(
            model_name='crontab',
            constraint=models.UniqueConstraint(fields=('seller', 'name'), name='unique_crontab'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('seller', 'name'), name='unique_metadata'),
        ),
        migrations.AddField(
            model_name='settings',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owm.seller', verbose_name='Связанный парсер'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.UniqueConstraint(fields=('seller', 'type'), name='unique_settings'),
        ),
    ]
