# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm', '0002_settings_alter_awaiting_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE owm_promoproduct "
                        "ADD COLUMN IF NOT EXISTS autoupdate_promo boolean NOT NULL DEFAULT FALSE;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE IF EXISTS owm_promoproduct "
                        "DROP COLUMN IF EXISTS autoupdate_promo;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='promoproduct',
                    name='autoupdate_promo',
                    field=models.BooleanField(default=False, verbose_name='Автообновление дней акции'),
                ),
            ],
        ),
    ]
