# Generated by Django 5.0.6 on 2025-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm', '0003_add_autoupdate_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoproduct',
            name='auto_update_days_limit_promo',
            field=models.BooleanField(default=False, verbose_name='Автообновление дней акции при достижении лимита'),
        ),
    ]
