# Generated by Django 5.0.6 on 2025-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm', '0004_promoproduct_auto_update_days_limit_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoproduct',
            name='min_price_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. цена автопринятия скидки'),
        ),
        migrations.AddField(
            model_name='promoproduct',
            name='use_discount',
            field=models.BooleanField(default=False, verbose_name='Автоматическое принятие скидки'),
        ),
    ]
